using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class StoryText : MonoBehaviour {

	// Use this for initialization
	void Start () {
		
	}
	
	// Update is called once per frame
	void Update () {
		
	}
}
//GOOD MORNING SIR, CONGRATULATIONS ON THE PROMOTION TO CEO.THE BOARD HOPES TO SEE MONUMENTAL GROWTH UNDER YOUR LEADERSHIP.
//LET’S GET STRAIGHT TO WORK THEN.
//DUE TO THE COMMERCIAL SUCCESS OF THE NUROSCAPE, IT APPEARS THAT WE HAVE 4.5 MILLION IN EXCESS SPENDING CAPITAL AVAILABLE. 
//YOU CAN INVEST THAT MONEY IN OTHER COMPANIES, INTERNAL RESEARCH AND DEVELOPMENT PROJECTS, OUR WORKFORCE, OR MIGHT I SUGGEST, USING IT TO COMMIT HOSTILE TAKEOVERS.
//THROUGH OUR INFORMANTS WITHIN A RIVAL CORPORATION KNOWN AS ARYA MEI, IT SEEMS AS IF THEY’RE WORKING ON A WAY TO INTERCONNECT THEIR EXOSKELETONS WITH HUMAN SPINAL CORDS.
//IF THIS HOLDS TRUE, ARYA MEI WOULD BE INFRINGING ON MULTIPLE OF OUR PATENTS.
//IT SEEMS AS IF A HOSTILE TAKE OVER IS OUR ONLY CHOICE.
